-- Seetal Pick · Supabase setup
-- Run this once in the Supabase SQL editor, then change the two sample
-- display names and passphrases at the bottom of this file.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  avatar_color text not null default '#ef6a56',
  passphrase_hash text not null,
  is_admin boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace view public.app_user_profiles as
  select id, display_name, avatar_color, active, created_at, is_admin
  from public.app_users;

create table if not exists public.pick_items (
  id uuid primary key default gen_random_uuid(),
  category_id text not null check (category_id in ('restaurants', 'takeaway', 'watch', 'activities')),
  name text not null,
  subtitle text,
  image_url text,
  genres text[] not null default array['Other'],
  tags text[] not null default '{}',
  source text not null default 'custom',
  source_id text,
  source_url text,
  added_by uuid references public.app_users(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.swipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  item_id uuid not null references public.pick_items(id) on delete cascade,
  decision text not null check (decision in ('yes', 'no')),
  swiped_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (user_id, item_id, swiped_on)
);

create table if not exists public.category_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  category_id text not null check (category_id in ('restaurants', 'takeaway', 'watch', 'activities')),
  filter_key text not null default 'all',
  session_date date not null default current_date,
  completed_at timestamptz not null default now(),
  unique (user_id, category_id, session_date, filter_key)
);

create table if not exists public.admin_sessions (
  token_hash bytea primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists pick_items_category_idx on public.pick_items(category_id, active);
create index if not exists swipes_day_idx on public.swipes(swiped_on, user_id);
create index if not exists category_sessions_day_idx on public.category_sessions(session_date, user_id);

alter table public.app_users enable row level security;
alter table public.pick_items enable row level security;
alter table public.swipes enable row level security;
alter table public.category_sessions enable row level security;
alter table public.admin_sessions enable row level security;

-- This is intentionally lightweight access control for a private, low-risk app.
-- The app_user_profiles view exposes names and colours, never passphrase hashes.
grant select on public.app_user_profiles to anon, authenticated;
grant select, insert on public.pick_items to anon, authenticated;
grant select, insert, update, delete on public.swipes to anon, authenticated;
grant select, insert, update, delete on public.category_sessions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "shared items readable" on public.pick_items;
create policy "shared items readable" on public.pick_items for select to anon, authenticated using (true);
drop policy if exists "shared items addable" on public.pick_items;
create policy "shared items addable" on public.pick_items for insert to anon, authenticated with check (true);
drop policy if exists "shared items editable" on public.pick_items;

drop policy if exists "swipes readable" on public.swipes;
create policy "swipes readable" on public.swipes for select to anon, authenticated using (true);
drop policy if exists "swipes addable" on public.swipes;
create policy "swipes addable" on public.swipes for insert to anon, authenticated with check (true);
drop policy if exists "swipes editable" on public.swipes;
create policy "swipes editable" on public.swipes for update to anon, authenticated using (true) with check (true);
drop policy if exists "swipes removable" on public.swipes;
create policy "swipes removable" on public.swipes for delete to anon, authenticated using (true);

drop policy if exists "sessions readable" on public.category_sessions;
create policy "sessions readable" on public.category_sessions for select to anon, authenticated using (true);
drop policy if exists "sessions addable" on public.category_sessions;
create policy "sessions addable" on public.category_sessions for insert to anon, authenticated with check (true);
drop policy if exists "sessions editable" on public.category_sessions;
create policy "sessions editable" on public.category_sessions for update to anon, authenticated using (true) with check (true);

drop function if exists public.login_with_passphrase(text);
create function public.login_with_passphrase(provided_passphrase text)
returns table (id uuid, display_name text, avatar_color text, is_admin boolean, admin_token text)
language plpgsql
security definer
set search_path = public
as $$
declare
  matched public.app_users%rowtype;
  raw_token text;
begin
  delete from public.admin_sessions where expires_at <= now();
  select u.* into matched
  from public.app_users u
  where u.active = true
    and u.passphrase_hash = crypt(provided_passphrase, u.passphrase_hash)
  limit 1;
  if not found then return; end if;
  if matched.is_admin then
    raw_token := encode(gen_random_bytes(32), 'hex');
    insert into public.admin_sessions (token_hash, user_id, expires_at)
    values (digest(raw_token, 'sha256'), matched.id, now() + interval '12 hours');
  end if;
  return query select matched.id, matched.display_name, matched.avatar_color, matched.is_admin, raw_token;
end;
$$;

revoke all on function public.login_with_passphrase(text) from public;
grant execute on function public.login_with_passphrase(text) to anon, authenticated;

create or replace function public.is_valid_admin_token(p_admin_token text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_sessions s
    join public.app_users u on u.id = s.user_id
    where s.token_hash = digest(coalesce(p_admin_token, ''), 'sha256')
      and s.expires_at > now() and u.active and u.is_admin
  );
$$;

create or replace function public.admin_update_item(p_admin_token text, p_item_id uuid, p_item jsonb)
returns setof public.pick_items
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_token(p_admin_token) then raise exception 'Admin session expired'; end if;
  return query
    update public.pick_items i set
      category_id = coalesce(nullif(p_item->>'categoryId', ''), i.category_id),
      name = coalesce(nullif(trim(p_item->>'name'), ''), i.name),
      subtitle = coalesce(p_item->>'subtitle', i.subtitle),
      image_url = coalesce(nullif(p_item->>'imageUrl', ''), i.image_url),
      genres = case when jsonb_typeof(p_item->'genres') = 'array' then array(select jsonb_array_elements_text(p_item->'genres')) else i.genres end,
      tags = case when jsonb_typeof(p_item->'tags') = 'array' then array(select jsonb_array_elements_text(p_item->'tags')) else i.tags end,
      source = coalesce(nullif(p_item->>'source', ''), i.source),
      source_id = nullif(p_item->>'sourceId', ''),
      source_url = nullif(p_item->>'sourceUrl', '')
    where i.id = p_item_id
    returning i.*;
end;
$$;

create or replace function public.admin_set_item_active(p_admin_token text, p_item_id uuid, p_active boolean)
returns setof public.pick_items
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_token(p_admin_token) then raise exception 'Admin session expired'; end if;
  return query update public.pick_items i set active = p_active where i.id = p_item_id returning i.*;
end;
$$;

create or replace function public.admin_delete_item(p_admin_token text, p_item_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_token(p_admin_token) then raise exception 'Admin session expired'; end if;
  delete from public.pick_items where id = p_item_id;
end;
$$;

create or replace function public.admin_import_items(p_admin_token text, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  entry jsonb;
  imported_count integer := 0;
  skipped_count integer := 0;
  category text;
  item_name text;
begin
  if not public.is_valid_admin_token(p_admin_token) then raise exception 'Admin session expired'; end if;
  if jsonb_typeof(p_items) <> 'array' then raise exception 'JSON must be an array'; end if;
  if jsonb_array_length(p_items) > 500 then raise exception 'Import is limited to 500 items'; end if;
  for entry in select value from jsonb_array_elements(p_items)
  loop
    category := entry->>'categoryId';
    item_name := trim(entry->>'name');
    if category not in ('restaurants', 'takeaway', 'watch', 'activities') or coalesce(item_name, '') = '' then
      raise exception 'Every item needs a valid categoryId and name';
    end if;
    if exists (select 1 from public.pick_items where category_id = category and lower(name) = lower(item_name)) then
      skipped_count := skipped_count + 1;
    else
      insert into public.pick_items (category_id, name, subtitle, image_url, genres, tags, source, source_id, source_url)
      values (
        category, item_name, coalesce(entry->>'subtitle', 'Added by JSON import'), nullif(entry->>'imageUrl', ''),
        case when jsonb_typeof(entry->'genres') = 'array' then array(select jsonb_array_elements_text(entry->'genres')) else array['Other'] end,
        case when jsonb_typeof(entry->'tags') = 'array' then array(select jsonb_array_elements_text(entry->'tags')) else '{}' end,
        coalesce(nullif(entry->>'source', ''), 'json-import'), nullif(entry->>'sourceId', ''), nullif(entry->>'sourceUrl', '')
      );
      imported_count := imported_count + 1;
    end if;
  end loop;
  return jsonb_build_object('imported', imported_count, 'skipped', skipped_count);
end;
$$;

revoke all on function public.is_valid_admin_token(text) from public;
revoke all on function public.admin_update_item(text, uuid, jsonb) from public;
revoke all on function public.admin_set_item_active(text, uuid, boolean) from public;
revoke all on function public.admin_delete_item(text, uuid) from public;
revoke all on function public.admin_import_items(text, jsonb) from public;
grant execute on function public.admin_update_item(text, uuid, jsonb) to anon, authenticated;
grant execute on function public.admin_set_item_active(text, uuid, boolean) to anon, authenticated;
grant execute on function public.admin_delete_item(text, uuid) to anon, authenticated;
grant execute on function public.admin_import_items(text, jsonb) to anon, authenticated;

-- Replace the names and passphrases below before sharing the app.
insert into public.app_users (id, display_name, avatar_color, passphrase_hash, is_admin)
values
  ('11111111-1111-4111-8111-111111111111', 'You', '#ef6a56', crypt('together', gen_salt('bf')), true),
  ('22222222-2222-4222-8222-222222222222', 'Partner', '#168a77', crypt('always', gen_salt('bf')), false)
on conflict (id) do nothing;

-- Starter cards. Add more through the app; these persist for every future day.
insert into public.pick_items (id, category_id, name, subtitle, image_url, tags, source)
values
  ('10000000-0000-4000-8000-000000000001', 'restaurants', 'Little Napoli', 'Cosy Italian · Handmade pasta · ££', 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=1200&q=86', array['Italian','Date night','Cosy'], 'starter'),
  ('10000000-0000-4000-8000-000000000002', 'restaurants', 'Koya House', 'Japanese · Sushi counter · £££', 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=86', array['Japanese','Sushi','Special'], 'starter'),
  ('10000000-0000-4000-8000-000000000003', 'restaurants', 'The Green Room', 'Modern British · Seasonal menu · ££', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=86', array['British','Local','Relaxed'], 'starter'),
  ('10000000-0000-4000-8000-000000000004', 'restaurants', 'Sol y Sal', 'Spanish · Small plates · ££', 'https://images.unsplash.com/photo-1516211697506-8360dbcfe9a4?auto=format&fit=crop&w=1200&q=86', array['Tapas','Sharing','Lively'], 'starter'),
  ('20000000-0000-4000-8000-000000000001', 'takeaway', 'Neapolitan pizza', 'Charred crusts, proper mozzarella, zero washing up', 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=86', array['Pizza','Comfort','Shareable'], 'starter'),
  ('20000000-0000-4000-8000-000000000002', 'takeaway', 'Thai night', 'Curries, noodles and something with a little kick', 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=86', array['Thai','Spicy','Cosy'], 'starter'),
  ('20000000-0000-4000-8000-000000000003', 'takeaway', 'Indian feast', 'A table full of curries, rice and too much naan', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=86', array['Indian','Feast','Vegetarian friendly'], 'starter'),
  ('20000000-0000-4000-8000-000000000004', 'takeaway', 'Tacos & sides', 'A messy, colourful, very good idea', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=86', array['Mexican','Fun','Shareable'], 'starter'),
  ('30000000-0000-4000-8000-000000000001', 'watch', 'The Bear', 'Comedy drama · 2022 · 30 min episodes', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=86', array['Series','Drama','Bingeable'], 'starter'),
  ('30000000-0000-4000-8000-000000000002', 'watch', 'Knives Out', 'Mystery comedy · 2019 · 2h 10m', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1200&q=86', array['Film','Mystery','Funny'], 'starter'),
  ('30000000-0000-4000-8000-000000000003', 'watch', 'Past Lives', 'Romance drama · 2023 · 1h 46m', 'https://images.unsplash.com/photo-1485095329183-d0797cdc5676?auto=format&fit=crop&w=1200&q=86', array['Film','Romance','Thoughtful'], 'starter'),
  ('30000000-0000-4000-8000-000000000004', 'watch', 'Only Murders in the Building', 'Mystery comedy · 2021 · 35 min episodes', 'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1200&q=86', array['Series','Mystery','Light'], 'starter'),
  ('40000000-0000-4000-8000-000000000001', 'activities', 'Pottery painting', 'Pick a piece, choose your colours and make a keepsake', 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=86', array['Creative','Indoors','2–3 hours'], 'starter'),
  ('40000000-0000-4000-8000-000000000002', 'activities', 'Golden-hour picnic', 'A blanket, favourite snacks and nowhere else to be', 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=86', array['Outdoors','Low-key','Romantic'], 'starter'),
  ('40000000-0000-4000-8000-000000000003', 'activities', 'Bowling rematch', 'One game, a little competition and questionable shoes', 'https://images.unsplash.com/photo-1538511059256-0b056e6d5c59?auto=format&fit=crop&w=1200&q=86', array['Playful','Indoors','1–2 hours'], 'starter'),
  ('40000000-0000-4000-8000-000000000004', 'activities', 'A new neighbourhood walk', 'Coffee in hand, phones away, choose turns as you go', 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=86', array['Free','Outdoors','Spontaneous'], 'starter')
on conflict (id) do nothing;

update public.pick_items set genres = case id
  when '10000000-0000-4000-8000-000000000001' then array['Italian']
  when '10000000-0000-4000-8000-000000000002' then array['Japanese']
  when '10000000-0000-4000-8000-000000000003' then array['British']
  when '10000000-0000-4000-8000-000000000004' then array['Mediterranean']
  when '20000000-0000-4000-8000-000000000001' then array['Pizza']
  when '20000000-0000-4000-8000-000000000002' then array['Thai']
  when '20000000-0000-4000-8000-000000000003' then array['Indian']
  when '20000000-0000-4000-8000-000000000004' then array['Mexican']
  when '30000000-0000-4000-8000-000000000001' then array['Comedy','Drama']
  when '30000000-0000-4000-8000-000000000002' then array['Mystery','Comedy']
  when '30000000-0000-4000-8000-000000000003' then array['Romance','Drama']
  when '30000000-0000-4000-8000-000000000004' then array['Mystery','Comedy']
  when '40000000-0000-4000-8000-000000000001' then array['Creative','Relaxed']
  when '40000000-0000-4000-8000-000000000002' then array['Outdoors','Relaxed','Food & drink']
  when '40000000-0000-4000-8000-000000000003' then array['Active','Games']
  when '40000000-0000-4000-8000-000000000004' then array['Outdoors','Day trip']
  else genres end
where source = 'starter';

notify pgrst, 'reload schema';
