-- Seetal Pick · Supabase setup
-- Run this once in the Supabase SQL editor, then change the two sample
-- display names and passphrases at the bottom of this file.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  avatar_color text not null default '#ef6a56',
  passphrase_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace view public.app_user_profiles as
  select id, display_name, avatar_color, active, created_at
  from public.app_users;

create table if not exists public.pick_items (
  id uuid primary key default gen_random_uuid(),
  category_id text not null check (category_id in ('restaurants', 'takeaway', 'watch', 'activities')),
  name text not null,
  subtitle text,
  image_url text,
  tags text[] not null default '{}',
  source text not null default 'custom',
  source_id text,
  source_url text,
  added_by uuid references public.app_users(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.swipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  item_id uuid not null references public.pick_items(id) on delete cascade,
  decision text not null check (decision in ('yes', 'no')),
  swiped_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (user_id, item_id, swiped_on)
);

create table if not exists public.category_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  category_id text not null check (category_id in ('restaurants', 'takeaway', 'watch', 'activities')),
  session_date date not null default current_date,
  completed_at timestamptz not null default now(),
  unique (user_id, category_id, session_date)
);

create index if not exists pick_items_category_idx on public.pick_items(category_id, active);
create index if not exists swipes_day_idx on public.swipes(swiped_on, user_id);
create index if not exists category_sessions_day_idx on public.category_sessions(session_date, user_id);

alter table public.app_users enable row level security;
alter table public.pick_items enable row level security;
alter table public.swipes enable row level security;
alter table public.category_sessions enable row level security;

-- This is intentionally lightweight access control for a private, low-risk app.
-- The app_user_profiles view exposes names and colours, never passphrase hashes.
grant select on public.app_user_profiles to anon, authenticated;
grant select, insert, update, delete on public.pick_items to anon, authenticated;
grant select, insert, update, delete on public.swipes to anon, authenticated;
grant select, insert, update, delete on public.category_sessions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "shared items readable" on public.pick_items;
create policy "shared items readable" on public.pick_items for select to anon, authenticated using (true);
drop policy if exists "shared items addable" on public.pick_items;
create policy "shared items addable" on public.pick_items for insert to anon, authenticated with check (true);
drop policy if exists "shared items editable" on public.pick_items;
create policy "shared items editable" on public.pick_items for update to anon, authenticated using (true) with check (true);

drop policy if exists "swipes readable" on public.swipes;
create policy "swipes readable" on public.swipes for select to anon, authenticated using (true);
drop policy if exists "swipes addable" on public.swipes;
create policy "swipes addable" on public.swipes for insert to anon, authenticated with check (true);
drop policy if exists "swipes editable" on public.swipes;
create policy "swipes editable" on public.swipes for update to anon, authenticated using (true) with check (true);
drop policy if exists "swipes removable" on public.swipes;
create policy "swipes removable" on public.swipes for delete to anon, authenticated using (true);

drop policy if exists "sessions readable" on public.category_sessions;
create policy "sessions readable" on public.category_sessions for select to anon, authenticated using (true);
drop policy if exists "sessions addable" on public.category_sessions;
create policy "sessions addable" on public.category_sessions for insert to anon, authenticated with check (true);
drop policy if exists "sessions editable" on public.category_sessions;
create policy "sessions editable" on public.category_sessions for update to anon, authenticated using (true) with check (true);

create or replace function public.login_with_passphrase(provided_passphrase text)
returns table (id uuid, display_name text, avatar_color text)
language sql
security definer
set search_path = public
as $$
  select u.id, u.display_name, u.avatar_color
  from public.app_users u
  where u.active = true
    and u.passphrase_hash = crypt(provided_passphrase, u.passphrase_hash)
  limit 1;
$$;

revoke all on function public.login_with_passphrase(text) from public;
grant execute on function public.login_with_passphrase(text) to anon, authenticated;

-- Replace the names and passphrases below before sharing the app.
insert into public.app_users (id, display_name, avatar_color, passphrase_hash)
values
  ('11111111-1111-4111-8111-111111111111', 'You', '#ef6a56', crypt('together', gen_salt('bf'))),
  ('22222222-2222-4222-8222-222222222222', 'Partner', '#168a77', crypt('always', gen_salt('bf')))
on conflict (id) do nothing;

-- Starter cards. Add more through the app; these persist for every future day.
insert into public.pick_items (id, category_id, name, subtitle, image_url, tags, source)
values
  ('10000000-0000-4000-8000-000000000001', 'restaurants', 'Little Napoli', 'Cosy Italian · Handmade pasta · ££', 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=1200&q=86', array['Italian','Date night','Cosy'], 'starter'),
  ('10000000-0000-4000-8000-000000000002', 'restaurants', 'Koya House', 'Japanese · Sushi counter · £££', 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=86', array['Japanese','Sushi','Special'], 'starter'),
  ('10000000-0000-4000-8000-000000000003', 'restaurants', 'The Green Room', 'Modern British · Seasonal menu · ££', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=86', array['British','Local','Relaxed'], 'starter'),
  ('10000000-0000-4000-8000-000000000004', 'restaurants', 'Sol y Sal', 'Spanish · Small plates · ££', 'https://images.unsplash.com/photo-1516211697506-8360dbcfe9a4?auto=format&fit=crop&w=1200&q=86', array['Tapas','Sharing','Lively'], 'starter'),
  ('20000000-0000-4000-8000-000000000001', 'takeaway', 'Neapolitan pizza', 'Charred crusts, proper mozzarella, zero washing up', 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=86', array['Pizza','Comfort','Shareable'], 'starter'),
  ('20000000-0000-4000-8000-000000000002', 'takeaway', 'Thai night', 'Curries, noodles and something with a little kick', 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=86', array['Thai','Spicy','Cosy'], 'starter'),
  ('20000000-0000-4000-8000-000000000003', 'takeaway', 'Indian feast', 'A table full of curries, rice and too much naan', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=86', array['Indian','Feast','Vegetarian friendly'], 'starter'),
  ('20000000-0000-4000-8000-000000000004', 'takeaway', 'Tacos & sides', 'A messy, colourful, very good idea', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=86', array['Mexican','Fun','Shareable'], 'starter'),
  ('30000000-0000-4000-8000-000000000001', 'watch', 'The Bear', 'Comedy drama · 2022 · 30 min episodes', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=86', array['Series','Drama','Bingeable'], 'starter'),
  ('30000000-0000-4000-8000-000000000002', 'watch', 'Knives Out', 'Mystery comedy · 2019 · 2h 10m', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1200&q=86', array['Film','Mystery','Funny'], 'starter'),
  ('30000000-0000-4000-8000-000000000003', 'watch', 'Past Lives', 'Romance drama · 2023 · 1h 46m', 'https://images.unsplash.com/photo-1485095329183-d0797cdc5676?auto=format&fit=crop&w=1200&q=86', array['Film','Romance','Thoughtful'], 'starter'),
  ('30000000-0000-4000-8000-000000000004', 'watch', 'Only Murders in the Building', 'Mystery comedy · 2021 · 35 min episodes', 'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1200&q=86', array['Series','Mystery','Light'], 'starter'),
  ('40000000-0000-4000-8000-000000000001', 'activities', 'Pottery painting', 'Pick a piece, choose your colours and make a keepsake', 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=86', array['Creative','Indoors','2–3 hours'], 'starter'),
  ('40000000-0000-4000-8000-000000000002', 'activities', 'Golden-hour picnic', 'A blanket, favourite snacks and nowhere else to be', 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=86', array['Outdoors','Low-key','Romantic'], 'starter'),
  ('40000000-0000-4000-8000-000000000003', 'activities', 'Bowling rematch', 'One game, a little competition and questionable shoes', 'https://images.unsplash.com/photo-1538511059256-0b056e6d5c59?auto=format&fit=crop&w=1200&q=86', array['Playful','Indoors','1–2 hours'], 'starter'),
  ('40000000-0000-4000-8000-000000000004', 'activities', 'A new neighbourhood walk', 'Coffee in hand, phones away, choose turns as you go', 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=86', array['Free','Outdoors','Spontaneous'], 'starter')
on conflict (id) do nothing;

notify pgrst, 'reload schema';

